"""empty message

Revision ID: 17e57e3f2e5c
Revises: 4d971a728abf
Create Date: 2022-01-10 19:23:37.264104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e57e3f2e5c'
down_revision = '4d971a728abf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_user', sa.Column('total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products_user', 'total')
    # ### end Alembic commands ###
