"""empty message

Revision ID: 534f0a305cb0
Revises: 883ab920392d
Create Date: 2022-01-08 17:28:09.450737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534f0a305cb0'
down_revision = '883ab920392d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cpf')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cpf', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
