"""empty message

Revision ID: d0f8119f41f4
Revises: 9193957da783
Create Date: 2022-01-10 13:11:34.818188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f8119f41f4'
down_revision = '9193957da783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('store_email_key', 'store', type_='unique')
    op.drop_column('store', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('email', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.create_unique_constraint('store_email_key', 'store', ['email'])
    # ### end Alembic commands ###
