class EmailAlreadyExistsError(Exception):
    ...


class InvalidKeyError(Exception):
    ...
class NotFoundError(Exception):
    ...

class InvalidTypeError(Exception):
    ...


class NotAcessibleError(Exception):
    ...

class UniqueUserError(Exception):
    ...
